word_emb: "word_embeddings"
pos_emb: "position_embeddings"
token_emb: "token_type_embeddings"
gamma: "LayerNorm/gamma"
beta: "LayerNorm/beta"
attn_query_kernal: "attention/self/query/kernel"
attn_query_bias: "attention/self/query/bias"
attn_key_kernal: "attention/self/key/kernel"
attn_key_bias: "attention/self/key/bias"
attn_value_kernal: "attention/self/value/kernel"
attn_value_bias: "attention/self/value/bias"
attn_dense_kernal: "attention/output/dense/kernel"
attn_dense_bias: "attention/output/dense/bias"
imdt_dense_kernal: "intermediate/dense/kernel"
imdt_dense_bias: "intermediate/dense/bias"
out_dense_kernal: "output/dense/kernel"
out_dense_bias: "output/dense/bias"
attn_out_gamma: "attention/output/LayerNorm/gamma"
attn_out_beta: "attention/output/LayerNorm/beta"
out_gamma: "output/LayerNorm/gamma"
out_beta: "output/LayerNorm/beta"
